# Generated by Django 4.0.5 on 2022-11-10 22:47

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copadomundo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdenacaoBrasileirao',
            new_name='Ordenacao',
        ),
        migrations.CreateModel(
            name='Ligas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
