# Generated by Django 4.0.5 on 2022-11-11 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copadomundo', '0002_rename_ordenacaobrasileirao_ordenacao_ligas'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ1',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ10',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ11',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ12',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ13',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ14',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ15',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ16',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ2',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ3',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ4',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ5',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ6',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ7',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ8',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='GrupoJ9',
            field=models.CharField(blank=True, choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='ligas',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
