# Generated by Django 4.0.5 on 2022-11-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copadomundo', '0003_horarios_grupoj1_horarios_grupoj10_horarios_grupoj11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='LocalJ1',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ10',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ11',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ12',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ13',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ14',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ15',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ16',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ2',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ3',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ4',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ5',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ6',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ7',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ8',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='LocalJ9',
            field=models.CharField(blank=True, choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30, null=True),
        ),
    ]
