# Generated by Django 4.0.5 on 2022-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copadomundo', '0004_horarios_localj1_horarios_localj10_horarios_localj11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='Time1J1',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J10',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J11',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J12',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J13',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J14',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J15',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J16',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J2',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J3',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J4',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J5',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J6',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J7',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J8',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time1J9',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J1',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J10',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J11',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J12',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J13',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J14',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J15',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J16',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J2',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J3',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J4',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J5',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J6',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J7',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J8',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='Time2J9',
            field=models.CharField(blank=True, choices=[('Catar', 'Catar'), ('Ecuador', 'Ecuador'), ('Holanda', 'Al Janoub, Al-Wakrah'), ('Senegal', 'Ahmad Bin Ali, Al Rayyan'), ('Estados Unidos', 'Al Thumama'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
    ]
