# Generated by Django 4.0.5 on 2022-11-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copadomundo', '0007_alter_horarios_time1j1_alter_horarios_time1j10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='Time1J1',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J10',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J11',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J12',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J13',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J14',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J15',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J16',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J2',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J3',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J4',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J5',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J6',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J7',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J8',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J9',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J1',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J10',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J11',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J12',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J13',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J14',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J15',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J16',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J2',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J3',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J4',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J5',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J6',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J7',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J8',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J9',
            field=models.CharField(blank=True, choices=[('Catar', 'CAT'), ('Equador', 'Equador'), ('Holanda', 'Holanda'), ('Senegal', 'Senegal'), ('Estados Unidos', 'Estados Unidos'), ('Inglaterra', 'Inglaterra'), ('Irã', 'Irã'), ('País de Gales', 'País de Gales'), ('Argentina', 'Argentina'), ('Arábia Saudita', 'Arábia Saudita'), ('México', 'México'), ('Polônia', 'Polônia'), ('Austrália', 'Austrália'), ('Dinamarca', 'Dinamarca'), ('França', 'França'), ('Tunísia', 'Tunísia'), ('Alemanha', 'Alemanha'), ('Costa Rica', 'Costa Rica'), ('Espanha', 'Espanha'), ('Japão', 'Japão'), ('Bélgica', 'Bélgica'), ('Canadá', 'Canadá'), ('Croácia', 'Croácia'), ('Marrocos', 'Marrocos'), ('Brasil', 'Brasil'), ('Camarões', 'Camarões'), ('Suíça', 'Suíça'), ('Sérvia', 'Sérvia'), ('Coreia do Sul', 'Coreia do Sul'), ('Gana', 'Gana'), ('Portugal', 'Portugal'), ('Uruguai', 'Uruguai')], max_length=30, null=True),
        ),
    ]
