# Generated by Django 4.0.5 on 2022-11-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copadomundo', '0008_alter_horarios_time1j1_alter_horarios_time1j10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='Time1J1',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J10',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J11',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J12',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J13',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J14',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J15',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J16',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J2',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J3',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J4',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J5',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J6',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J7',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J8',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time1J9',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J1',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J10',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J11',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J12',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J13',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J14',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J15',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J16',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J2',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J3',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J4',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J5',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J6',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J7',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J8',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Time2J9',
            field=models.CharField(blank=True, choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30, null=True),
        ),
    ]
