# Generated by Django 4.0.5 on 2022-11-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copadomundo', '0009_alter_horarios_time1j1_alter_horarios_time1j10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rodada', models.IntegerField()),
                ('Jogo', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], max_length=2)),
                ('Horario', models.DateTimeField(verbose_name='data/hora')),
                ('Grupo', models.CharField(choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H')], max_length=8)),
                ('Local', models.CharField(choices=[('Khalifa International, Doha', 'Khalifa International, Doha'), ('Al Bayt, Al Khor', 'Al Bayt, Al Khor'), ('Al Janoub, Al-Wakrah', 'Al Janoub, Al-Wakrah'), ('Ahmad Bin Ali, Al Rayyan', 'Ahmad Bin Ali, Al Rayyan'), ('Al Thumama', 'Al Thumama'), ('Education City, Doha', 'Education City, Doha'), ('974, Doha', '974, Doha'), ('Lusail Iconic Stadium, Lusail', 'Lusail Iconic Stadium, Lusail')], max_length=30)),
                ('Time1', models.CharField(choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30)),
                ('Time2', models.CharField(choices=[('CAT', 'Catar'), ('EQU', 'Equador'), ('HOL', 'Holanda'), ('SEN', 'Senegal'), ('EUA', 'Estados Unidos'), ('ING', 'Inglaterra'), ('IRA', 'Irã'), ('GAL', 'País de Gales'), ('ARG', 'Argentina'), ('ARA', 'Arábia Saudita'), ('MEX', 'México'), ('POL', 'Polônia'), ('AUS', 'Austrália'), ('DIN', 'Dinamarca'), ('FRA', 'França'), ('TUN', 'Tunísia'), ('ALE', 'Alemanha'), ('CRC', 'Costa Rica'), ('ESP', 'Espanha'), ('JAP', 'Japão'), ('BEL', 'Bélgica'), ('CAN', 'Canadá'), ('CRO', 'Croácia'), ('MAR', 'Marrocos'), ('BRA', 'Brasil'), ('CAM', 'Camarões'), ('SUI', 'Suíça'), ('SER', 'Sérvia'), ('COR', 'Coreia do Sul'), ('GAN', 'Gana'), ('POR', 'Portugal'), ('URU', 'Uruguai')], max_length=30)),
            ],
        ),
    ]
