# Generated by Django 4.0.5 on 2022-11-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copadomundo', '0013_rename_ale_palpites_time1_rename_arg_palpites_time2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palpites',
            name='Jogo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
