# Generated by Django 4.0.5 on 2022-11-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copadomundo', '0014_palpites_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palpites',
            name='time1',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)]),
        ),
        migrations.AlterField(
            model_name='palpites',
            name='time2',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)]),
        ),
    ]
