# Generated by Django 4.0.5 on 2022-07-01 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athleticoPR', models.IntegerField()),
                ('libertad', models.IntegerField()),
                ('fortaleza', models.IntegerField()),
                ('estudiantes', models.IntegerField()),
                ('cerroPorteno', models.IntegerField()),
                ('palmeiras', models.IntegerField()),
                ('emelec', models.IntegerField()),
                ('atleticoMG', models.IntegerField()),
                ('tolima', models.IntegerField()),
                ('flamengo', models.IntegerField()),
                ('corinthians', models.IntegerField()),
                ('bocaJuniors', models.IntegerField()),
                ('talleres', models.IntegerField()),
                ('colon', models.IntegerField()),
                ('velezSarsfield', models.IntegerField()),
                ('riverPlate', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
