# Generated by Django 4.0.5 on 2022-07-02 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brasileirao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AthleticoPR', models.IntegerField()),
                ('Palmeiras', models.IntegerField()),
                ('Corinthians', models.IntegerField()),
                ('Internacional', models.IntegerField()),
                ('AtleticoMG', models.IntegerField()),
                ('Fluminense', models.IntegerField()),
                ('Santos', models.IntegerField()),
                ('SaoPaulo', models.IntegerField()),
                ('Flamengo', models.IntegerField()),
                ('Botafogo', models.IntegerField()),
                ('Avai', models.IntegerField()),
                ('Bragantino', models.IntegerField()),
                ('AtleticoGO', models.IntegerField()),
                ('Goias', models.IntegerField()),
                ('Ceara', models.IntegerField()),
                ('Coritiba', models.IntegerField()),
                ('AmericaMG', models.IntegerField()),
                ('Cuiaba', models.IntegerField()),
                ('Juventude', models.IntegerField()),
                ('Fortaleza', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
