# Generated by Django 4.0.5 on 2022-08-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontuacaobrasileirao',
            name='Jogo1',
        ),
        migrations.RemoveField(
            model_name='pontuacaobrasileirao',
            name='Jogo10',
        ),
        migrations.RemoveField(
            model_name='pontuacaobrasileirao',
            name='Jogo2',
        ),
        migrations.RemoveField(
            model_name='pontuacaobrasileirao',
            name='Jogo3',
        ),
        migrations.RemoveField(
            model_name='pontuacaobrasileirao',
            name='Jogo4',
        ),
        migrations.RemoveField(
            model_name='pontuacaobrasileirao',
            name='Jogo5',
        ),
        migrations.RemoveField(
            model_name='pontuacaobrasileirao',
            name='Jogo6',
        ),
        migrations.RemoveField(
            model_name='pontuacaobrasileirao',
            name='Jogo7',
        ),
        migrations.RemoveField(
            model_name='pontuacaobrasileirao',
            name='Jogo8',
        ),
        migrations.RemoveField(
            model_name='pontuacaobrasileirao',
            name='Jogo9',
        ),
    ]
