# Generated by Django 4.0.5 on 2022-07-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brasileirao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadosBrasileirao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rodada', models.CharField(choices=[('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38')], max_length=2)),
                ('AthleticoPR', models.IntegerField()),
                ('Palmeiras', models.IntegerField()),
                ('Corinthians', models.IntegerField()),
                ('Internacional', models.IntegerField()),
                ('AtleticoMG', models.IntegerField()),
                ('Fluminense', models.IntegerField()),
                ('Santos', models.IntegerField()),
                ('SaoPaulo', models.IntegerField()),
                ('Flamengo', models.IntegerField()),
                ('Botafogo', models.IntegerField()),
                ('Avai', models.IntegerField()),
                ('Bragantino', models.IntegerField()),
                ('AtleticoGO', models.IntegerField()),
                ('Goias', models.IntegerField()),
                ('Ceara', models.IntegerField()),
                ('Coritiba', models.IntegerField()),
                ('AmericaMG', models.IntegerField()),
                ('Cuiaba', models.IntegerField()),
                ('Juventude', models.IntegerField()),
                ('Fortaleza', models.IntegerField()),
            ],
        ),
    ]
