# Generated by Django 4.0.5 on 2022-10-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pontuacaobrasileirao_rodada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='AthleticoPR',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
