# Generated by Django 4.0.5 on 2022-09-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pontuacaototalbrasileirao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacaobrasileirao',
            name='Rodada',
            field=models.IntegerField(choices=[(15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38')], max_length=2),
        ),
    ]
