# Generated by Django 4.0.5 on 2022-10-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_resultadosbrasileirao_athleticopr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='AmericaMG',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='AtleticoGO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='AtleticoMG',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Avai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Botafogo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Bragantino',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Ceara',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Corinthians',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Coritiba',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Cuiaba',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Flamengo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Fluminense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Fortaleza',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Goias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Internacional',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Juventude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Palmeiras',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='Santos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosbrasileirao',
            name='SaoPaulo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
