# Generated by Django 4.0.5 on 2022-10-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_resultadosbrasileirao_americamg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacaobrasileirao',
            name='RB',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pontuacaobrasileirao',
            name='RE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pontuacaobrasileirao',
            name='RP',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pontuacaototalbrasileirao',
            name='RB',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pontuacaototalbrasileirao',
            name='RE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pontuacaototalbrasileirao',
            name='RP',
            field=models.IntegerField(null=True),
        ),
    ]
