# Generated by Django 4.0.5 on 2022-10-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pontuacaobrasileirao_rb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuacaobrasileirao',
            name='ER',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pontuacaototalbrasileirao',
            name='ER',
            field=models.IntegerField(null=True),
        ),
    ]
