# Generated by Django 4.0.5 on 2022-10-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_resultadosbrasileirao_rodada_copadobrasil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copadobrasil',
            old_name='CorinthiansPenalti',
            new_name='Penalti',
        ),
        migrations.RemoveField(
            model_name='copadobrasil',
            name='FlamengoPenalti',
        ),
    ]
