# Generated by Django 4.0.5 on 2024-03-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_palpitesformula1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palpitesformula1',
            name='Equipe',
            field=models.CharField(blank=True, choices=[('Red Bull Racing', 'Red Bull Racing'), ('Williams', 'Williams'), ('AlphaTauri', 'AlphaTauri'), ('McLaren', 'McLaren'), ('Alpine', 'Alpine'), ('Aston Martin Racing', 'Aston Martin Racing'), ('Hass F1 Team', 'Hass F1 Team'), ('Sauber', 'Sauber'), ('Ferrari', 'Ferrari'), ('Mercedes', 'Mercedes')], max_length=20, null=True),
        ),
    ]
