# Generated by Django 4.0.5 on 2024-03-20 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_pontuacaototalf1_pontuacaof1'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalpitesPGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FaZe_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('FaZe_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Spirit_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Spirit_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Vitality_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Vitality_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('MOUZ_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('MOUZ_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Virtuspro_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Virtuspro_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('NatusVincere_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('NatusVincere_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('G2_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('G2_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Complexity_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Complexity_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Heroic_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Heroic_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Cloud9_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Cloud9_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('EternalFire_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('EternalFire_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('paiN_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('paiN_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('ECSTATIC_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('ECSTATIC_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('TheMongolz_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('TheMongolz_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Imperial_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('Imperial_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('FURIA_V', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('FURIA_D', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
