# Generated by Django 4.0.5 on 2024-03-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rodada', models.IntegerField()),
                ('Jogo', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)], max_length=2)),
                ('Horario', models.DateTimeField(verbose_name='data/hora')),
                ('Local', models.CharField(choices=[('ARENA DO GRÊMIO ', 'ARENA DO GRÊMIO '), ('MINEIRÃO', 'MINEIRÃO'), ('NEO QUÍMICA ARENA', 'NEO QUÍMICA ARENA'), ('ILHA DO RETIRO', 'ILHA DO RETIRO'), ('MORUMBI', 'MORUMBI'), ('INDEPENDÊNCIA', 'INDEPENDÊNCIA'), ('BEIRA-RIO', 'BEIRA-RIO'), ('ARENA DA BAIXADA', 'ARENA DA BAIXADA'), ('NILTON SANTOS', 'NILTON SANTOS'), ('MARACANÃ', 'MARACANÃ'), ('VILA BELMIRO', 'VILA BELMIRO'), ('ITAIPAVA ARENA FONTE NOVA', 'ITAIPAVA ARENA FONTE NOVA'), ('ALLIANZ PARQUE', 'ALLIANZ PARQUE'), ('CASTELÃO (CE)', 'CASTELÃO (CE)')], max_length=30)),
                ('Time1', models.CharField(choices=[('CAM', 'Atlético-MG'), ('COR', 'Corinthians'), ('SPT', 'Sport'), ('SPO', 'São Paulo'), ('AME', 'América-MG'), ('INT', 'Internacional'), ('CAP', 'Athletico-PR'), ('BOT', 'Botafogo'), ('FLU', 'Fluminense'), ('FLA', 'Flamengo'), ('SAN', 'Santos'), ('BAH', 'Bahia'), ('PAL', 'Palmeiras'), ('FOR', 'Fortaleza')], max_length=30)),
                ('Time2', models.CharField(choices=[('CAM', 'Atlético-MG'), ('COR', 'Corinthians'), ('SPT', 'Sport'), ('SPO', 'São Paulo'), ('AME', 'América-MG'), ('INT', 'Internacional'), ('CAP', 'Athletico-PR'), ('BOT', 'Botafogo'), ('FLU', 'Fluminense'), ('FLA', 'Flamengo'), ('SAN', 'Santos'), ('BAH', 'Bahia'), ('PAL', 'Palmeiras'), ('FOR', 'Fortaleza')], max_length=30)),
            ],
        ),
    ]
